import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { GoogleOAuthProvider } from '@react-oauth/google';
import { Toaster } from "react-hot-toast";
import Provider from "@/components/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
     <html lang="en">
    <body className={inter.className}>
    <Provider>
    <GoogleOAuthProvider clientId="630940048159-75e8gbgo49tanvv0joo3tr6laf7ut1na.apps.googleusercontent.com">
     {children}
    <Toaster/>
    </GoogleOAuthProvider>
    </Provider>
    </body>
   </html>
  );
}
